### ISSUE TITLE
Memento 

### ISSUE THREAD

**Issue by kevinchr** [aryaminus/memento#1]
Hey

Sorry to bother you so soon already but i really got excited when i saw that you update memento and wanted to give it a spin. 

So i installed everything on ubuntu to get it working and made a map inside memento and did python memento.py memes, then the script runs and when i enter 1 or any other number and get this message( see attachment) How can i fix this? 

I don't think it has anything to do with tesseract, because i did a tesseract ocr on an image with an output to .txt and it extracted the data..

Have i missed installing a module or something? 

Hope you can help me out :)

![memento screenshot](https://user-images.githubusercontent.com/10005359/39399152-2c9ed61a-4b19-11e8-9f30-faf95d7c4e44.png)

**Comment by aryaminus** [comment]
The input() is taking `prompt` as integer not string. Try executing using python3 instead of python. Else put `choice = input().strip()` instead of `choice = input().lower().strip()` in memento.py line 29. Let me know which one works

**Comment by kevinchr** [comment]
Hey man i finally got it to work! So sweet and it's so fast! Oh yeah and how could i make the extracted text to save a little longer, because now it doesn't write down the full sentence to the image file?
